AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  {"createdOn":"Linux","createdBy":"Amplify","createdWith":"12.10.1","stackType":"queue-SQS","metadata":{}}
Parameters:
  env:
    Type: String
Resources:
  ErrorsQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      ContentBasedDeduplication: true
      QueueName:
        Fn::Join:
          - ''
          - - errors-queue-
            - Ref: env
            - .fifo
  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: ErrorsQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - SQS:DeleteMessage
              - SQS:GetQueueAttributes
            Resource:
              Fn::GetAtt:
                - ErrorsQueue
                - Arn
Outputs:
  QueueURL:
    Description: URL of new Amazon SQS Queue
    Value:
      Ref: ErrorsQueue
  QueueARN:
    Description: ARN of new Amazon SQS Queue
    Value:
      Fn::GetAtt:
        - ErrorsQueue
        - Arn
  QueueName:
    Description: Name new Amazon SQS Queue
    Value:
      Fn::GetAtt:
        - ErrorsQueue
        - QueueName
